{"name": "Проверка: если передать несуществующий трек, вернётся ошибка 404", "status": "passed", "start": 1710504336605, "stop": 1710504337155, "uuid": "f2c4bb79-95c8-4d9d-b605-e8e537e5195d", "historyId": "0255818dd5b574d77d9509e71b8ae82e", "testCaseId": "0255818dd5b574d77d9509e71b8ae82e", "fullName": "tests.tests_order.test_get_order_by_track.TestGetOrderByTrack#test_get_order_by_invalid_track_causes_404_error", "labels": [{"name": "parentSuite", "value": "tests.tests_order"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderByTrack"}, {"name": "host", "value": "Olyas-MacBook-Air.local"}, {"name": "thread", "value": "78521-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_order.test_get_order_by_track"}]}